package network.skypvp.extraction.item;

import java.util.List;
import java.util.Locale;
import net.kyori.adventure.text.format.TextColor;
import org.bukkit.NamespacedKey;
import org.bukkit.entity.Player;

/**
 * Cosmetic skin catalog for raid backpacks. Every tier ships the same 19 variants
 * (imported from Eclipse-Studios/backpacks by Import-BackpackModels.ps1); the item model
 * key is {@code skypvp:backpack_t<tier>_<skin>} so a skin survives tier upgrades by id.
 *
 * <p>Unlocks are permission-driven ({@code skypvp.backpack.skin.<id>}): granting the node
 * through LuckPerms is the persistence layer, no extra storage. {@link #DEFAULT_ID} is
 * always available. The wearer's CHOICE is stored in {@link BackpackPayload#skin()} so it
 * travels inside the item like everything else.
 */
public final class BackpackSkins {

    /** One selectable look. {@code color} tints names/lore in the selector. */
    public record Skin(String id, String displayName, TextColor color) {
    }

    public static final String DEFAULT_ID = "brown";
    public static final String PERMISSION_PREFIX = "skypvp.backpack.skin.";

    public static final List<Skin> ALL = List.of(
            new Skin("brown", "Classic Brown", TextColor.color(0x8a5a3b)),
            new Skin("black", "Onyx", TextColor.color(0x555555)),
            new Skin("gray", "Slate", TextColor.color(0x8f8f8f)),
            new Skin("light_gray", "Ash", TextColor.color(0xbdbdbd)),
            new Skin("white", "Arctic", TextColor.color(0xf5f5f5)),
            new Skin("red", "Crimson", TextColor.color(0xe04040)),
            new Skin("orange", "Ember", TextColor.color(0xf28c28)),
            new Skin("yellow", "Sandstorm", TextColor.color(0xf2d024)),
            new Skin("lime", "Toxin", TextColor.color(0x8ae234)),
            new Skin("green", "Jungle", TextColor.color(0x3f9e4d)),
            new Skin("cyan", "Lagoon", TextColor.color(0x2fbdbd)),
            new Skin("light_blue", "Skyline", TextColor.color(0x6fc3f2)),
            new Skin("blue", "Abyss", TextColor.color(0x3b6ff2)),
            new Skin("purple", "Void", TextColor.color(0x9a4ff2)),
            new Skin("magenta", "Neon", TextColor.color(0xe051d5)),
            new Skin("pink", "Bubblegum", TextColor.color(0xf29ac9)),
            new Skin("autumnal", "Autumnal", TextColor.color(0xc76b2e)),
            new Skin("christmas", "Festive", TextColor.color(0x4fc46f)),
            new Skin("nether", "Netherborn", TextColor.color(0xb3312c))
    );

    private BackpackSkins() {
    }

    /** Resolves a stored id; unknown/legacy ids fall back to the default skin. */
    public static Skin byId(String id) {
        if (id != null) {
            String normalized = id.trim().toLowerCase(Locale.ROOT);
            for (Skin skin : ALL) {
                if (skin.id().equals(normalized)) {
                    return skin;
                }
            }
        }
        return byId(DEFAULT_ID);
    }

    public static boolean exists(String id) {
        if (id == null) {
            return false;
        }
        String normalized = id.trim().toLowerCase(Locale.ROOT);
        return ALL.stream().anyMatch(skin -> skin.id().equals(normalized));
    }

    /** {@code skypvp:backpack_t<tier>_<skin>} — generated by Import-BackpackModels.ps1. */
    public static NamespacedKey modelKey(int tier, String skinId) {
        int clamped = Math.max(1, Math.min(BackpackDefinition.MAX_TIER, tier));
        return new NamespacedKey("skypvp", "backpack_t" + clamped + "_" + byId(skinId).id());
    }

    public static String permission(String skinId) {
        return PERMISSION_PREFIX + byId(skinId).id();
    }

    /** The default skin is free; everything else rides its LuckPerms node. */
    public static boolean isUnlocked(Player player, String skinId) {
        Skin skin = byId(skinId);
        return DEFAULT_ID.equals(skin.id())
                || (player != null && player.hasPermission(permission(skin.id())));
    }
}
