package network.skypvp.extraction.item;

import network.skypvp.paper.item.api.CustomItemDefinition;
import network.skypvp.paper.item.api.CustomItemTypeId;
import network.skypvp.paper.item.api.ItemCategory;
import org.bukkit.Material;

public final class MedicConsumableDefinition implements CustomItemDefinition {

    private final MedicConsumableType type;

    public MedicConsumableDefinition(MedicConsumableType type) {
        this.type = type;
    }

    public MedicConsumableType medicType() {
        return type;
    }

    @Override
    public CustomItemTypeId typeId() {
        return type.typeId();
    }

    @Override
    public String modeKey() {
        return "extraction";
    }

    @Override
    public ItemCategory category() {
        return ItemCategory.CONSUMABLE;
    }

    @Override
    public Material displayMaterial() {
        return type.material();
    }

    @Override
    public java.util.Optional<org.bukkit.NamespacedKey> itemModel() {
        // Per-type art from the skypvp pack: every consumable id has a dedicated
        // "medic_<id>" sprite (items/medic_<id>.json), generated by
        // infra/scripts/Generate-CraftingItemArt.ps1.
        return java.util.Optional.of(new org.bukkit.NamespacedKey("skypvp", "medic_" + type.id()));
    }

    @Override
    public boolean stackable() {
        // Deterministic instance ids so identical consumables merge — raid inventories
        // were drowning in single medkits/syringes. Cap comes from ItemConfigOverrides
        // (stats.stackSize in crafting/items/medic_<id>.json).
        return true;
    }

    @Override
    public int schemaVersion() {
        return 1;
    }
}
